name = "baobeigushi"
compatibility_date = "2023-12-01"

[build]
command = ""
cwd = ""
watch_dir = ""

[[pages_build_output_dir]]
directory = "."

[env.production]
vars = { NODE_ENV = "production" }